//! Scan crate for Deepsys security scanner.
//!
//! This crate defines the core scanning logic and interfaces for different
//! types of security scanners.

use deepsys_types::{ScanResult, ScanTarget, SecurityIssue, Vulnerability, Severity};
use async_trait::async_trait;
use thiserror::Error;
use std::time::Duration;
use chrono::Utc;
use uuid::Uuid;
use std::collections::HashMap;

/// Errors that can occur during scanning.
#[derive(Error, Debug)]
pub enum ScanError {
    #[error("Scan failed for target {target}: {message}")]
    ScanFailed {
        target: ScanTarget,
        message: String,
    },
    #[error("Scanner not initialized: {0}")]
    NotInitialized(String),
    #[error("Invalid scan configuration: {0}")]
    InvalidConfig(String),
    #[error("Unknown scan error: {0}")]
    Unknown(String),
}

/// Result type for scan operations.
pub type Result<T> = std::result::Result<T, ScanError>;

/// Trait for security scanners.
#[async_trait]
pub trait Scanner {
    /// Performs a scan on the given target and returns a ScanResult.
    async fn scan(&self, target: ScanTarget) -> Result<ScanResult>;
}

/// A mock scanner for testing and initial development.
/// It generates a predefined ScanResult.
pub struct MockScanner;

#[async_trait]
impl Scanner for MockScanner {
    async fn scan(&self, target: ScanTarget) -> Result<ScanResult> {
        let mut scan_result = ScanResult::new(target.clone());

        // Simulate some scan duration
        tokio::time::sleep(Duration::from_millis(100)).await;

        // Add a mock vulnerability
        let vuln = Vulnerability {
            id: "CVE-MOCK-001".to_string(),
            package_name: "mock-package".to_string(),
            package_version: "1.0.0".to_string(),
            severity: Severity::High,
            title: "Mock Vulnerability".to_string(),
            description: "This is a mock vulnerability generated by MockScanner.".to_string(),
            cvss_score: Some(7.5),
            cvss_vector: None,
            references: vec!["http://example.com/mock-cve".to_string()],
            fixed_version: Some("1.0.1".to_string()),
            published_date: Some(Utc::now()),
            last_modified_date: Some(Utc::now()),
            data_source: None,
            custom_fields: HashMap::new(),
        };
        scan_result.add_issue(SecurityIssue::Vulnerability(vuln));

        // Update duration and return
        scan_result.duration = Utc::now().signed_duration_since(scan_result.timestamp).to_std().unwrap_or_default();
        Ok(scan_result)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use deepsys_types::ScanTarget;

    #[tokio::test]
    async fn test_mock_scanner() {
        let scanner = MockScanner;
        let target = ScanTarget::Filesystem {
            path: "/mock/path".to_string(),
            recursive: true,
        };

        let scan_result = scanner.scan(target.clone()).await.unwrap();

        assert_eq!(scan_result.target, target);
        assert_eq!(scan_result.issues.len(), 1);
        if let SecurityIssue::Vulnerability(vuln) = &scan_result.issues[0] {
            assert_eq!(vuln.id, "CVE-MOCK-001");
            assert_eq!(vuln.severity, Severity::High);
        } else {
            panic!("Expected a vulnerability issue");
        }
        assert!(scan_result.duration.as_millis() > 0);
    }
}